[theme]
primaryColor = "#007BFF"  # A classic blue for primary highlights
backgroundColor = "#F2F4F8"  # A soft gray for the main background
secondaryBackgroundColor = "#E8ECEF"  # A lighter gray for sections
textColor = "#2C3E50"  # A dark blue-gray for contrast
font = "monospace"  # Use a coding font
